// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace gtmGame
{
	
	

	// Defined in table: ItemCfg
	
	public partial class ItemCfg
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// Item
		/// </summary>
		public List<ItemDefine> Item = new List<ItemDefine>(); 
	
	
		#region Index code
	 	Dictionary<long, ItemDefine> _ItemByID = new Dictionary<long, ItemDefine>();
        public ItemDefine GetItemByID(long ID, ItemDefine def = default(ItemDefine))
        {
            ItemDefine ret;
            if ( _ItemByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(ItemDefine) )
			{
				TableLogger.ErrorLine("GetItemByID failed, ID: {0}", ID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
		#region Deserialize code
		
		static tabtoy.DeserializeHandler<ItemCfg> _ItemCfgDeserializeHandler;
		static tabtoy.DeserializeHandler<ItemCfg> ItemCfgDeserializeHandler
		{
			get
			{
				if (_ItemCfgDeserializeHandler == null )
				{
					_ItemCfgDeserializeHandler = new tabtoy.DeserializeHandler<ItemCfg>(Deserialize);
				}

				return _ItemCfgDeserializeHandler;
			}
		}
		public static void Deserialize( ItemCfg ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.Item.Add( reader.ReadStruct<ItemDefine>(ItemDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build Item Index
			for( int i = 0;i< ins.Item.Count;i++)
			{
				var element = ins.Item[i];
				
				ins._ItemByID.Add(element.ID, element);
				
			}
			
		}
		static tabtoy.DeserializeHandler<ItemDefine> _ItemDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<ItemDefine> ItemDefineDeserializeHandler
		{
			get
			{
				if (_ItemDefineDeserializeHandler == null )
				{
					_ItemDefineDeserializeHandler = new tabtoy.DeserializeHandler<ItemDefine>(Deserialize);
				}

				return _ItemDefineDeserializeHandler;
			}
		}
		public static void Deserialize( ItemDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x20000:
                	{
						ins.ID = reader.ReadInt64();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Name = reader.ReadString();
                	}
                	break; 
                	case 0x60002:
                	{
						ins.Desc = reader.ReadString();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
	

	} 

	// Defined in table: Item
	[System.Serializable]
	public partial class ItemDefine
	{
	
		
		/// <summary> 
		/// 唯一ID
		/// </summary>
		public long ID = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 描述
		/// </summary>
		public string Desc = ""; 
	
	

	} 

}
