// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace gtmGame
{
	
	

	// Defined in table: TsInfoCfg
	
	public partial class TsInfoCfg
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// TsInfo
		/// </summary>
		public List<TsInfoDefine> TsInfo = new List<TsInfoDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, TsInfoDefine> _TsInfoByID = new Dictionary<int, TsInfoDefine>();
        public TsInfoDefine GetTsInfoByID(int ID, TsInfoDefine def = default(TsInfoDefine))
        {
            TsInfoDefine ret;
            if ( _TsInfoByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(TsInfoDefine) )
			{
				TableLogger.ErrorLine("GetTsInfoByID failed, ID: {0}", ID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
		#region Deserialize code
		
		static tabtoy.DeserializeHandler<TsInfoCfg> _TsInfoCfgDeserializeHandler;
		static tabtoy.DeserializeHandler<TsInfoCfg> TsInfoCfgDeserializeHandler
		{
			get
			{
				if (_TsInfoCfgDeserializeHandler == null )
				{
					_TsInfoCfgDeserializeHandler = new tabtoy.DeserializeHandler<TsInfoCfg>(Deserialize);
				}

				return _TsInfoCfgDeserializeHandler;
			}
		}
		public static void Deserialize( TsInfoCfg ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.TsInfo.Add( reader.ReadStruct<TsInfoDefine>(TsInfoDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build TsInfo Index
			for( int i = 0;i< ins.TsInfo.Count;i++)
			{
				var element = ins.TsInfo[i];
				
				ins._TsInfoByID.Add(element.ID, element);
				
			}
			
		}
		static tabtoy.DeserializeHandler<TsInfoDefine> _TsInfoDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<TsInfoDefine> TsInfoDefineDeserializeHandler
		{
			get
			{
				if (_TsInfoDefineDeserializeHandler == null )
				{
					_TsInfoDefineDeserializeHandler = new tabtoy.DeserializeHandler<TsInfoDefine>(Deserialize);
				}

				return _TsInfoDefineDeserializeHandler;
			}
		}
		public static void Deserialize( TsInfoDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.ID = reader.ReadInt32();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Name = reader.ReadString();
                	}
                	break; 
                	case 0x60002:
                	{
						ins.Desc = reader.ReadString();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
	

	} 

	// Defined in table: TsInfo
	[System.Serializable]
	public partial class TsInfoDefine
	{
	
		
		/// <summary> 
		/// 唯一ID
		/// </summary>
		public int ID = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 描述
		/// </summary>
		public string Desc = ""; 
	
	

	} 

}
