// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0

package table

var (
    TS_Login_Failed = 100001  // 登录失败
    TS_Login_Success = 100002  // 登录成功
    TS_Login_CreateName_Failed = 100100  // 创建名字失败
    TS_Login_CreateName_Succeed = 100101  // 创建名字成功
    TS_Login_Account_Empty = 100200  // 输入账号为空
    TS_Login_Passward_Empty = 100201  // 输入密码为空
    TS_RegAcc_Success = 200001  // 注册账号成功
    TS_RegAcc_Failed = 200002  // 注册账号失败，账号创建失败
    TS_RegAcc_Exist = 200003  // 注册账号失败，账号已经存在
    TS_RegAcc_Test = 200004  // 注册账号测试
)
