import sys
import os
import xlrd

def export_files(cfg_data_list, dstfilepath):
    filecontent = "-- AutoGen //"
    filecontent += "\n\n"
    filecontent += "TsInfoEnum = {\n"

    for cfg_data in cfg_data_list:
        cfg_id = cfg_data[0]
        cfg_name = cfg_data[1]
        filecontent += "    " + cfg_name + " = " + str(cfg_id) + ",\n"

    filecontent += "}\n\n"

    # 保存
    dstfilefullpath = dstfilepath + "/TsInfoEnum.lua"
    file = open(dstfilefullpath, "wb")
    file.write(filecontent.encode())
    file.close()

def export_files_go(cfg_data_list, dstfilepath):
    filecontent = "// Generated by github.com/davyxu/tabtoy\n"
    filecontent += "// Version: 2.9.0\n\n"

    filecontent += "package table\n\n"
    filecontent += "var (\n"

    for cfg_data in cfg_data_list:
        cfg_id = cfg_data[0]
        cfg_name = cfg_data[1]
        cfg_desc = cfg_data[2]
        filecontent += "    " + cfg_name + " = " + str(cfg_id) + "  // " + cfg_desc + "\n"

    filecontent += ")\n"

    # 保存
    dstfilefullpath = dstfilepath + "/TsInfoEnum.go"
    file = open(dstfilefullpath, "wb")
    file.write(filecontent.encode())
    file.close()

def fillCfgData(cfg_data_list, cfg_dir, cfg_name):
    excel = xlrd.open_workbook(cfg_dir + "/" + cfg_name)
    sheet1 = excel.sheet_by_index(0)
    rows = sheet1.nrows

    for rowidx in range(4, rows):
        row = sheet1.row_values(rowidx)
        cfg_id = int(row[0])
        cfg_name = row[1]
        cfg_desc = row[2]

        cfg_data = []
        cfg_data.append(cfg_id)
        cfg_data.append(cfg_name)
        cfg_data.append(cfg_desc)
        cfg_data_list.append(cfg_data)


def main():
    cfg_dir = sys.argv[1]
    cfg_name = sys.argv[2]
    lua_c_dstdir = sys.argv[3]
    lua_s_dstdir = sys.argv[4]
    go_s_dstdir = sys.argv[5]

    # cfg_dir = "../../doc/"
    # cfg_name = "TsInfo.xlsx"
    # lua_c_dstdir = "../../client/client/Assets/StreamingAssets/lua/cfg/"
    # lua_s_dstdir = "../../server/cfg/"

    print(cfg_dir)
    print(cfg_name)
    print(lua_c_dstdir)
    print(lua_s_dstdir)

    cfg_data_list = []
    fillCfgData(cfg_data_list, cfg_dir, cfg_name)
    export_files(cfg_data_list, lua_c_dstdir)
    export_files(cfg_data_list, lua_s_dstdir)
    export_files_go(cfg_data_list, go_s_dstdir)

if __name__ == '__main__':
    main()



