-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.0

ConfigMgr = {}

ConfigMgr.Hero = require "Cfg.Hero"
ConfigMgr.Item = require "Cfg.Item"
ConfigMgr.Scene = require "Cfg.Scene"
ConfigMgr.ServerList = require "Cfg.ServerList"
ConfigMgr.TsInfo = require "Cfg.TsInfo"

return ConfigMgr
