-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.0

configmgr = {}

configmgr.Hero = require "cfg.Hero"
configmgr.Item = require "cfg.Item"
configmgr.Scene = require "cfg.Scene"
configmgr.ServerList = require "cfg.ServerList"
configmgr.TsInfo = require "cfg.TsInfo"

return configmgr
